### ISSUE TITLE
Getting started links to wrong boost version download

### ISSUE THREAD

**Issue by alxgb** [boostorg/more#1]
https://www.boost.org/doc/libs/1_69_0/more/getting_started/windows.html, 
https://www.boost.org/doc/libs/1_69_0/more/getting_started/unix-variants.html and the 1.68 equivalent pages link to the 1.67 download.

To be honest, the only reason I realized was because I came across a bug that affected 1.67 specifically and had a reply on June/July that mentioned it being fixed in master. I was sure I had viewed the latest version on the guide, but also surprised there would have been no release since last summer, so I decided to double check...

**Comment by glenfe** [comment]
This should be fixed now (in Boost versions 1.75 and higher)
