### ISSUE TITLE
The latest documentation in www.boost.org/doc/ does not reflect the same version

### ISSUE THREAD

**Issue by yoonghm** [boostorg/more#2]
The source document for "Getting Started" is in rst format.  It seems that it could handle version number. However, I do not see the right version in the html format.

For example, from [https://www.boost.org/doc/libs/1_69_0/more/getting_started/unix-variants.html](https://www.boost.org/doc/libs/1_69_0/more/getting_started/unix-variants.html), readers are directed to download version 1.67.0 instead of 1.69.0.

**Comment by glenfe** [comment]
Should be fixed since v1.75
